export const navigation_tabs = 'navigation.tabs'

export const screen_login = 'screens.login'
export const screen_createApplication = 'screens.createApplication'
export const screen_newApplication = 'screens.newApplication'
export const screen_replenishment = 'screens.replenishment'
export const screen_order = 'screens.order'
export const screen_profile = 'screens.profile'
export const screen_editProfile = 'screens.editProfile'
export const screen_addCard = 'screens.addCard'
export const screen_myService = 'screens.myService'
export const screen_myGoodDeed = 'screens.myGoodDeed'
export const screen_requestGoodDeed = 'screens.requestGoodDeed'
export const screen_revard = 'screens.revard'
export const screen_bankCard = 'screens.bankCard'
export const screen_requstService = 'screens.requstService'
export const screen_responses = 'screens.responses'
export const screen_executer = 'screens.executer'
export const screen_readReview = 'screens.readReview'
export const screen_lostItems = 'screens.lostItems'

export const component_home = 'components.home'
export const component_profile = 'components.profile'

export const utils_util_name = 'utils.util_name'

export const component_modal = 'components.modal'
