export const navigation_tabs = 'navigation.tabs'

export const screen_login = 'screens.login'
export const screen_createApplication = 'screens.createApplication'
export const screen_newApplication = 'screens.newApplication'
export const screen_replenishment = 'screens.replenishment'
export const screen_order = 'screens.order'
export const screen_profile = 'screens.profile'
export const screen_editProfile = 'screens.editProfile'
export const screen_addCard = 'screens.addCard'
export const screen_myService = 'screens.myService'
export const screen_myGoodDeed = 'screens.myGoodDeed'
export const screen_requestGoodDeed = 'screens.requestGoodDeed'
export const screen_revard = 'screens.revard'
export const screen_bankCard = 'screens.bankCard'
export const screen_requstService = 'screens.requstService'
export const screen_responses = 'screens.responses'
export const screen_executer = 'screens.executer'
export const screen_readReview = 'screens.readReview'
export const screen_lostItems = 'screens.lostItems'

export const screen_home = 'screens.home'
export const screen_service = 'screens.service'
export const screen_application = 'screens.application'
export const screen_findApplication = 'screens.findApplication'
export const screen_review = 'screens.review'
export const screen_findRoom = 'screens.findRoom'
export const screen_notification = 'screens.notification'

export const utils_util_name = 'utils.util_name'

//navigations
export const home_stack = 'navigation.homeStack'
export const index = 'navigation.index'
