export const ROOT_MAIN = 'rootMain'

// STACK
export const STACK_HOME = 'HomeStack'
export const STACK_PROFILE = 'ProfileStack'

// SCREENS
export const SCREEN_HOME = 'HomeScreen'
export const SCREEN_LOGIN = 'LoginScreen'
export const SCREEN_PROFILE = 'ProfilScreen'
export const SCREEN_EDIT_PROFILE = 'EditProfileScreen'
export const SCREEN_ADD_CARD = 'AddCardScreen'
export const SCREEN_SERVICE = 'ServiceScreen'
export const SCREEN_LOST_ITEMS = 'LostItemsScreen'
export const SCREEN_NOTIFICATIONS = 'NotificationsScreen'
export const SCREEN_APPLICATION = 'ApplicationScreen'
export const SCREEN_CHAT = 'ChatScreen'
export const SCREEN_CREATE_APPLICATION = 'CreateApplicationScreen'
export const SCREEN_NEW_APPLICATION = 'NewApplicationScreen'
export const SCREEN_REPLENISHMENT = 'ReplenishmentScreen'
export const SCREEN_ORDER = 'OrderScreen'
export const SCREEN_REVIEW = 'ScreenReview'
export const SCREEN_FINDROOM = 'FindRoomScreen'
export const SCREEN_MYSERVICE = 'MyServiceScreen'
export const SCREEN_MYGOODDEED = 'MyGoodDeedScreen'
export const SCREEN_REQUESTSERVICE = 'RequestService'
export const SCREEN_FIND_SEARCH = 'FindSearchScreen'
export const SCREEN_FIND_APPLICATION = 'FindApplicationScreen'
